### DEV ###
---
spring:
  application:
    name: uoo-monitor
server:
  port: 30000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config:
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
...
### DEV END ###

### FAT ###
---
spring:
  application:
    name: FAT-uoo-monitor-1
  profiles: FAT-uoo-monitor-1
server:
  port: 20000
eureka:
  client:
    service-url:
      defaultZone: http://FAT-uoo-register-1:8761/eureka/, http://FAT-uoo-register-2:8762/eureka/
turbine:
  app-config:
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
...
---
spring:
  application:
    name: FAT-uoo-monitor-2
  profiles: FAT-uoo-monitor-2
server:
  port: 20001
eureka:
  client:
    service-url:
      defaultZone: http://FAT-uoo-register-1:8761/eureka/, http://FAT-uoo-register-2:8762/eureka/
turbine:
  app-config:
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
...
### FAT END ###

### PROD ###
# 生产环境配置
# 暂无
### PROD END ###
