spring:
  application:
    name: business-syn-msg
  datasource:
      druid:
        url: jdbc:oracle:thin:@134.96.167.19:1521:uomdb1
        driver-class-name:  oracle.jdbc.OracleDriver
        username: octopus
        password: octopus
        initial-size: 10
        min-idle: 4
        max-active: 30
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        validationQueryTimeout: 5
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        filter:
          stat:
            enabled: true
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          slf4j:
            enabled: true
            connection-log-enabled: true
            connection-close-after-log-enabled: true
            connection-commit-after-log-enabled: true
            connection-connect-after-log-enabled: true
            connection-connect-before-log-enabled: true
            connection-log-error-enabled: true
            data-source-log-enabled: true
            result-set-log-enabled: true
            statement-log-enabled: true
          wall:
            enabled: true
            config:
              alter-table-allow: false
              truncate-allow: false
              drop-table-allow: false
              #是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL
              none-base-statement-allow: false
              #检查UPDATE语句是否无where条件，这是有风险的，但不是SQL注入类型的风险
              update-where-none-check: true
              #SELECT ... INTO OUTFILE 是否允许，这个是mysql注入攻击的常见手段，缺省是禁止的
              select-into-outfile-allow: false
              #是否允许调用Connection.getMetadata方法，这个方法调用会暴露数据库的表信息
              metadata-allow: true
              #允许多条sql一起执行
              multiStatementAllow: true
            #对被认为是攻击的SQL进行LOG.error输出
            log-violation: true
            #对被认为是攻击的SQL抛出SQLExcepton
            throw-exception: true
            #db-type: mysql
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
          #你可以配置principalSessionName，使得druid能够知道当前的cookie的用户是谁
          #principal-cookie-name: admin
          #你可以配置principalSessionName，使得druid能够知道当前的session的用户是谁
          #principal-session-name: admin
          #设置profileEnable能够监控单个url调用的sql列表。
          profile-enable: true
          #session统计功能
          session-stat-enable: false
          #最大session数
          session-stat-max-count: 100000
        stat-view-servlet:
          #allow: ${GATEWAY_HOST:172.26.114.241}
          enabled: true
          login-username: ${DRUID_USER:admin}
          login-password: ${DRUID_PWD:admin}
          url-pattern: /druid/*
          #允许清除记录
          reset-enable: false
  #      aop-patterns: cn.ffcs.uoo.**.service.*

  rabbitmq:
    username: root
    password: 123
    host: 134.96.253.221
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:mapper/**Mapper.xml
  typeAliasesPackage: cn.ffcs.uoo
  global-config:
    id-type: 1
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

server:
  port: 11000

eureka:
  instance:
    appname: business-syn-msg
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    port: 8762
  client:
    service-url:
      defaultZone:  http://localhost:${eureka.server.port}/eureka/

feign:
  hystrix:
    enable:true

logging:
  level:
    cn.ffcs.uoo: info
  config: classpath:log.xml
  path: ./rock/jpa-test3/log