server:
  port: 18022
spring:
  application:
    name: mdm-web
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/
  devtools:
    livereload:
      enabled: true

eureka:
  client:
    service-url:
      #defaultZone: http://134.96.253.221:${eureka.server.port}/eureka/
      defaultZone:  http://134.96.253.221:8751/eureka/,http://134.96.253.222:8751/eureka/,http://134.96.253.223:8751/eureka/
      #defaultZone: http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  server:
    port: 8751
feign:
  hystrix:
    enabled: true

  httpclient:
    enabled: true
    max-connections: 200 # 默认值
    max-connections-per-route: 50 # 默认值

hystrix:
  enabled: true
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000

logging:
  level:
    cn.ffcs.uoo.web: debug