server:
  port: 9092
spring:
  application:
    name: mdm-web
  mvc: 
    static-path-pattern: /**
  resources: 
    static-locations: classpath:/templates/,classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/
  devtools: 
    livereload: 
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${eureka.server.port}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  server:
    port: 8762
feign:
  hystrix:
    enabled: true
    shareSecurityContext: true
    command:
      default:
        circuitBreaker:
          sleepWindowInMilliseconds: 100000
          forceClosed: true
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 600000
#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000

logging:
  level:
    cn.ffcs.uoo.web: debug