server:
  port: 9090
spring:
  application:
    name: uoo-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.server.port}/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  server:
    port: 8762

logging:
  level: warn