/*
TRUNCATE TABLE LOG_ACCESS;
DROP TABLE LOG_ACCESS;
*/
CREATE TABLE LOG_ACCESS(
     LOG_CA_ID NUMBER(12),
     CLAZZ VARCHAR(400),
     METHOD VARCHAR(100),
     IP VARCHAR(100),
     URLS VARCHAR(400),
     USER_ID NUMBER(12),
     OPERATE VARCHAR(10),
     COST_MILLIS NUMBER(12),
     ARGS CLOB,
     RESPONSE CLOB,
     CREATE_DATE DATE

 )
PARTITION BY RANGE(CREATE_DATE)
 (
     PARTITION PART_01 VALUES LESS THAN (TO_DATE('2019-01-01 00:00:00','yyyy-mm-dd hh24:mi:ss')) TABLESPACE USERS,
     PARTITION PART_02 VALUES LESS THAN (TO_DATE('2019-02-01 00:00:00','yyyy-mm-dd hh24:mi:ss')) TABLESPACE USERS,
     PARTITION PART_03 VALUES LESS THAN (TO_DATE('2019-03-01 00:00:00','yyyy-mm-dd hh24:mi:ss')) TABLESPACE USERS
);

ALTER TABLE LOG_ACCESS ADD CONSTRAINT PK_LOG_ACCESS PRIMARY KEY(LOG_CA_ID);

CREATE SEQUENCE SEQ_LOG_ACCESS_ID
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE;