server:
  port: XXX
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://134.96.253.222:8751/eureka/,http://134.96.253.223:8751/eureka/