### DEV ###
---
server:
  port: 11100
  #port: 30024
spring:
  application:
    name: uoo-organization
  # 目前使用的是我的阿里云上的mysql数据库
  datasource:
    url: jdbc:oracle:thin:@134.96.167.19:1521:uomdb1
    username: octopus
    password: octopus
  zipkin:
    base-url: http://localhost:20010
  sleuth:
    sampler:
      percentage: 1.0
  data:
    solr:
      host: http://localhost:8888/uooSolr
      #host: http://134.96.253.221:8762/uooSolr
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      #defaultZone: http://134.96.253.221:8762/eureka
      defaultZone: http://localhost:8762/eureka
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-column-underline: true
    field-strategy: 2
    id-type: 1
    refresh-mapper: true
...
### DEV END ###

### FAT ###
---
server:
  port: 30020
spring:
  application:
    name: FAT-uoo-organization-1
  profiles: FAT-uoo-organization-1
  # 目前使用的是我的阿里云上的mysql数据库
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=true&useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:20010
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://FAT-uoo-register-1:8761/eureka/, http://FAT-uoo-register-2:8762/eureka/
mybatis-plus:
  mapper-locations: classpath:mapper/**Mapper.xml
...
---
server:
  port: 30021
spring:
  application:
    name: FAT-uoo-organization-2
  profiles: FAT-uoo-organization-2
  # 目前使用的是我的阿里云上的mysql数据库
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=true&useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:20010
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://FAT-uoo-register-1:8761/eureka/, http://FAT-uoo-register-2:8762/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
...
### FAT END ###

### PROD ###
# 生产环境配置
# 暂无
### PROD END ###
