### DEV ###
---
spring:
  application:
    name: uoo-register
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
...
### DEV END ###

### FAT ###
---
spring:
  application:
    name: uoo-register
  profiles: FAT-uoo-register-1
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://FAT-uoo-register-2:8762/eureka/
...
---
spring:
  application:
    name: uoo-register
  profiles: FAT-uoo-register-2
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://FAT-uoo-register-1:8761/eureka/
...
### FAT END ###

### PROD ###
# 生产环境配置
# 暂无
### PROD END ###
