spring:
  profiles: 231
eureka:
  instance:
    hostname: 134.96.217.231
  client:
    serviceUrl:
      defaultZone: http://134.96.217.232:8751/eureka/,http://134.96.217.233:8751/eureka/
server:
  port: 8751

---
spring:
  profiles: 232
eureka:
  instance:
    hostname: 134.96.217.232
  client:
    serviceUrl:
      defaultZone: http://134.96.217.231:8751/eureka/,http://134.96.217.233:8751/eureka/
server:
  port: 8751

---
spring:
  profiles: 233
eureka:
  instance:
    hostname: 134.96.217.233
  client:
    serviceUrl:
      defaultZone: http://134.96.217.231:8751/eureka/,http://134.96.217.232:8751/eureka/
server:
  port: 8751