spring:
  application:
    name: business-user
server:
  port: 11300
mybatis-plus:
  mapper-locations: classpath:mapper/**Mapper.xml
  typeAliasesPackage: cn.ffcs.uoo
  global-config:
    id-type: 1
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    meta-object-handler: cn.ffcs.uoo.core.user.util.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  #路由超时，即socket超时设置
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

logging:
  level:
    cn.ffcs.uoo: info

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: pro