### DEV ###
---
server:
  port: 30030
spring:
  application:
    name: uoo-region-provider
  datasource:
    url: jdbc:oracle:thin:@134.96.167.19:1521:uomdb1
    username: octopus
    password: octopus
  zipkin:
    base-url: http://localhost:20010
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: ccn.ffcs.uoo.core.region.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
...
### DEV END ###

### FAT ###
---
server:
  port: 30030
spring:
  application:
    name: uoo-region-provider
  datasource:
    url: jdbc:oracle:thin:@134.96.167.19:1521:uomdb1
    username: octopus
    password: octopus
  zipkin:
    base-url: http://localhost:20010
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: ccn.ffcs.uoo.core.region.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
...
---
server:
  port: 30031
spring:
  application:
    name: uoo-region-provider
  datasource:
    url: jdbc:oracle:thin:@134.96.167.19:1521:uomdb1
    username: octopus
    password: octopus
  zipkin:
    base-url: http://localhost:20010
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: ccn.ffcs.uoo.core.region.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
...
### FAT END ###

### PROD ###
# 生产环境配置
# 暂无
### PROD END ###
