### DEV ###
---
spring:
  application:
    name: uoo-gateway
server:
  port: 20010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
...
### DEV END ###

### FAT ###
---
spring:
  application:
    name: FAT-uoo-gateway-1
  profiles: FAT-uoo-gateway-1
server:
  port: 20010
eureka:
  client:
    service-url:
      defaultZone: http://FAT-uoo-register-1:8761/eureka/, http://FAT-uoo-register-2:8762/eureka/
...
---
spring:
  application:
    name: FAT-uoo-gateway-2
  profiles: FAT-uoo-gateway-2
server:
  port: 20011
eureka:
  client:
    service-url:
      defaultZone: http://FAT-uoo-register-1:8761/eureka/, http://FAT-uoo-register-2:8762/eureka/
...
### FAT END ###

### PROD ###
# 生产环境配置
# 暂无
### PROD END ###
